[
  # Erlang v24.x
  {"lib/commanded/event/upcaster.ex", :unknown_function},
  {"lib/commanded/serialization/json_decoder.ex", :unknown_function},

  # Erlang v23.x
  {":0:unknown_function Function Commanded.Event.Upcaster.Atom.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.BitString.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Float.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Function.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Integer.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.List.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Map.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.PID.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Port.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Reference.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Event.Upcaster.Tuple.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Atom.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.BitString.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Float.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Function.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Integer.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.List.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Map.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.PID.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Port.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Reference.__impl__/1 does not exist.",
   :unknown_function},
  {":0:unknown_function Function Commanded.Serialization.JsonDecoder.Tuple.__impl__/1 does not exist.",
   :unknown_function}
]
